#page title
page_title: Blockfuture                                         # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id: 1527943538                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link:                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link:                                           # Enter Google Play Store URL.
presskit_download_link: https://merunas.org                                          # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
# Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").
app_icon: assets/appicon.png # assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name: Blockfuture                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price: Free                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description: Read the top 100 timeless hand-picked cryptocurrency and blockchain articles on the go with Blockfuture for free

enable_smart_app_banner: true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Merunas Grincalaitis                                
your_link                                 : https://merunas.org
your_city                                 : Madrid                                
email_address                             : merunasgrincalaitis@gmail.com
facebook_username                         :                                           
instagram_username                        : merunas
twitter_username                          : merunas2
github_username                           : merlox
youtube_username                          : merunas



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Learn about crypto daily
    description                           : Everyday 10 handpicked articles about crypto and blockchain are added for you
    fontawesome_icon_name                 : magic
    
  - title                                 : Let the experts choose for you
    description                           : The articles expire every 24 hours so you always get the freshest content without any decision fatigue
    fontawesome_icon_name                 : mobile

  - title                                 : Dark mode enabled
    description                           : Whether you're a night reader or a day reader, we got you covered
    fontawesome_icon_name                 : play-circle

  - title                                 : Beautiful and comfortable interface
    description                           : With a clean and minimalistic design you'll enjoy reading everyday
    fontawesome_icon_name                 : sync

  - title                                 : Perfect font size
    description                           : So your eyes don't get strained by reading comfortably while getting the most words per line
    fontawesome_icon_name                 : adjust
  
  - title                                 : Technical and not so much
    description                           : Articles for those of you experienced with the technicalities of the Blockchain and for those that enjoy a more relaxed reading
    fontawesome_icon_name                 : star

  - title                                 : Traders welcome
    description                           : If you are an avid crypto trader you'll find some excellent pieces of content to improve your profits
    fontawesome_icon_name                 : arrow-alt-circle-down

  - title                                 : Make a profit
    description                           : Don't miss the next huge crypto boom to make a massive profit in days before anyone else
    fontawesome_icon_name                 : link

  - title                                 : The hard parts made easy
    description                           : Only the best curated articles pass the selection process to the app so you understand crypto concepts in plain English
    fontawesome_icon_name                 : info-circle

  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown